name: mep_dubai_AI
description: Dubai MEP AI practice app (EN/AR) with dynamic daily questions.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  http: ^1.2.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/questions/
